### ISSUE TITLE
Integration of This With Azure B2C?

### ISSUE THREAD

**Issue by rcnjstudent** [martincostello/SignInWithAppleSample#49]
Those of us using Azure B2C for Sign in With Apple are struggling with it a bit since it doesn't return all of the values from the Apple callback that your script does.  Particularly, the First Name, Last Name, Email Address (even if anonymized with Private Email feature) since that only gets sent once during the initial signup.  Sign in With Apple seems to be kind of a half baked idea with them and we're not sure why they're dragging their feet on this.  Is there any chance that we can take aspects of your script and make it work with Azure B2C to capture that info in the callback?

**Comment by martincostello** [comment]
I'm not familiar with Azure B2C to know what that would entail.

The code for the Apple provider that comes via NuGet is here: https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/tree/dev/src/AspNet.Security.OAuth.Apple

I would imagine that the relevant bits would be the code that extract the claims from the Apple-provided JWT, assuming you can get access to it during the authentication/authorization flow in Azure B2C:

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/b475447c3b5e456cca0f954a9b9c0772b6bedd4a/src/AspNet.Security.OAuth.Apple/AppleAuthenticationHandler.cs#L108-L118

https://github.com/aspnet-contrib/AspNet.Security.OAuth.Providers/blob/b475447c3b5e456cca0f954a9b9c0772b6bedd4a/src/AspNet.Security.OAuth.Apple/AppleEmailClaimAction.cs#L26-L34
